movies/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('new/', views.new, name='new' ),
    path('create/', views.create, name='create' ),
    path('', views.index, name='index' ),
    path('<int:movie_pk>/', views.detail, name='detail' ),
    path('<int:movie_pk>/edit/', views.edit, name='edit' ),
    path('<int:movie_pk>/update/', views.update, name='update' ),
    path('<int:movie_pk>/delete/', views.delete, name='delete' ),
    path('search/', views.search, name='search' ),
]

pjt04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/models.py
from django.db import models
from django.db import models

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    poster_path = models.CharField(max_length=500)

    def __str__(self):
        return self.title

movies/views.py
from movies.models import Movie
from django.shortcuts import redirect, render

# Create your views here.

# 새로운 글 작성 페이지 반환
def new(request):
    return render(request, 'movies/new.html')

# 작성하면 models에 반영 => detail로 redirect
def create(request):
    title = request.POST.get('title')
    overview = request.POST.get('overview')
    poster_path = request.POST.get('poster_path')
    movie = Movie(title=title, overview=overview, poster_path=poster_path)
    movie.save()

    return redirect('movies:detail', movie.pk)

# 전체 영화 목록 페이지(HOME) 반환
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

# 세부 영화 페이지 반환
def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)

# 세부 영화 수정 페이지 반환
def edit(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/edit.html', context)

# 수정하면 models에 반영 => detail로 redirect
def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.title = request.POST.get('title')
    movie.overview = request.POST.get('overview')
    movie.poster_path = request.POST.get('poster_path')
    movie.save()

    return redirect('movies:detail', movie.pk)

# 삭제하면 models에 반영 => index로 redirect
def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie.pk)

def search(request):
    query = request.GET.get('query')
    movies = Movie.objects.filter(title__icontains=query)
    print(movies)
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context) 

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% comment %} 세부 영화 조회 {% endcomment %}

{% block content %}
  <div class="container w-70">
    <br>
    <div class="d-flex">
      <img src="{{ movie.poster_path }}" alt="영화이미지" width="500px" class="m-5">
      <div class="d-flex flex-column m-5 justify-content-between w-100">
        <div>
          <h2 class="text-center text-secondary mt-3 mb-5">{{ movie.title }}</h2>
          <h5 class="text-secondary">{{ movie.overview }}</h5>
        </div>
        <div class="d-flex justify-content-end">
          <a href ="{% url 'movies:edit' movie.pk %}" class="mx-1">
            <button class="btn btn-success">
              MODIFY
            </button>
          </a>
          <form action="{% url 'movies:delete' movie.pk %}" method="POST" class="mx-1">
            {% csrf_token %}
            <button class="btn btn-secondary">DELETE</button>
          </form>
        </div>
      </div>
    </div>




  </div>
  <br><br>

{% endblock content %}

movies/templates/movies/edit.html
{% extends 'base.html' %}
{% comment %} 글 수정 {% endcomment %}

{% block content %}
    <br><br>
    <form action="{% url 'movies:update' movie.pk %}" method="POST" class="container my-5 ms-auto me-auto text-center fw-bold">
      {% csrf_token %}
      <div class="d-flex flex-column" width="300px">
        <div class="my-3 d-flex">
          <label for="title" class="d-block me-2">MOVIE TITLE</label>
          <input type="text" id="title" name="title" class="d-block w-100" autofocus value="{{ movie.title }}">
        </div>
        <div class="d-flex my-3">
          <label for="overview" class="d-block me-3">OVERVIEW</label>
          <textarea name="overview" id="overview" cols="30" rows="10" class="d-block w-100">{{ movie.overview }}</textarea>
        </div>
        <div class="d-flex my-3">
          <label for="poster_path" class="d-block me-2">POSTER URL</label>
          <input type="text" id="poster_path" name="poster_path" class="d-block w-100" value="{{ movie.poster_path }}">
        </div>
      </div>
      <button class="btn btn-success my-3 d-block ms-auto">COMPLETE</button>
    </form>
{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% comment %} 전체 목록 조회 {% endcomment %}

{% block content %}
  <br><br>
  <section class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-4">
      {% for movie in movies %}
        <article class="col">
          <div class="card">
            <a href="{% url 'movies:detail' movie.pk %}" class="text-decoration-none text-dark"><img src="{{ movie.poster_path }}" class="card-img-top" alt="..."></a>
            <div class="card-body">
              <h5 class="card-title text-center"><a href="{% url 'movies:detail' movie.pk %}" class="text-decoration-none text-dark">
                {{ movie.title }}
              </a></h5>
            </div>
          </div>
        </article>
      {% endfor %}
    </div>
  </section>
  <br><br>
{% endblock content %}

movies/templates/movies/new.html
{% extends 'base.html' %}
{% comment %} 새로운 글 작성 {% endcomment %}

{% block content %}
    <br><br>
    <form action="{% url 'movies:create' %}" method="POST" class="container my-5 ms-auto me-auto text-center fw-bold">
      {% csrf_token %}
      <div class="d-flex flex-column" width="300px">
        <div class="my-3 d-flex">
          <label for="title" class="d-block me-2">MOVIE TITLE</label>
          <input type="text" id="title" name="title" class="d-block w-100" autofocus>
        </div>
        <div class="d-flex my-3">
          <label for="overview" class="d-block me-3">OVERVIEW</label>
          <textarea name="overview" id="overview" cols="30" rows="10" class="d-block w-100"></textarea>
        </div>
        <div class="d-flex my-3">
          <label for="poster_path" class="d-block me-2">POSTER URL</label>
          <input type="text" id="poster_path" name="poster_path" class="d-block w-100">
        </div>
      </div>
      <button class="btn btn-success my-3 d-block ms-auto">COMPLETE</button>
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>MOVIES</title>
    <style>
      * {
        font-family: 'Raleway', sans-serif;
      }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand fw-bold text-success ms-3" href="{% url 'movies:index' %}">MOVIES</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active ms-3" aria-current="page" href="{% url 'movies:index' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active ms-3" aria-current="page" href="{% url 'movies:new' %}">NEW</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'movies:search' %}" method="GET">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="m-5">
  {% block content %}
  {% endblock content %}
</div>

<footer class="d-flex fixed-bottom bg-light justify-content-center align-items-center p-2 text-success">
  <p class="m-2">- Chuseok movies recommended by Kisol Kim -</p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>    
</body>

</html>